line-length = 88
preview = true

[lint]
select = ["E", "F", "UP", "B", "I", "SIM", "S", "RUF", "PTH", "C4", "ARG", "G"]
extend-select = ["RUF029"]
fixable = ["ALL"]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101"]